name: Swift

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild build test -scheme "peerdid-swift" -destination "platform=macOS" -resultBundlePath TestResults
